# Generated by Django 6.1.1 on 2026-09-10 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('route_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('route_name', models.CharField(max_length=200)),
                ('service_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BusStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_seq', models.IntegerField()),
                ('stop_village_name', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=100)),
                ('taluk', models.CharField(max_length=100)),
                ('stop_category', models.CharField(max_length=100)),
                ('cumulative_dist_km', models.FloatField()),
                ('stop_dwell_min', models.IntegerField()),
                ('cumulative_travel_time_min', models.IntegerField()),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='tracker.route')),
            ],
            options={
                'ordering': ['stop_seq'],
                'unique_together': {('route', 'stop_seq')},
            },
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_number', models.CharField(max_length=30)),
                ('is_live', models.BooleanField(default=False)),
                ('tracking_mode', models.CharField(choices=[('REAL', 'Real GPS'), ('DEMO', 'Demo Mode')], default='DEMO', max_length=10)),
                ('current_stop_seq', models.IntegerField(default=1)),
                ('current_latitude', models.FloatField(blank=True, null=True)),
                ('current_longitude', models.FloatField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('LIVE', 'Live'), ('STOPPED', 'Stopped'), ('DELAYED', 'Delayed'), ('OFFLINE', 'Offline'), ('COMPLETED', 'Completed')], default='OFFLINE', max_length=20)),
                ('stopped_since', models.DateTimeField(blank=True, null=True)),
                ('stop_reason', models.CharField(blank=True, max_length=200, null=True)),
                ('destination_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ending_buses', to='tracker.busstop')),
                ('start_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starting_buses', to='tracker.busstop')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buses', to='tracker.driver')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buses', to='tracker.route')),
            ],
        ),
    ]
