# Generated by Django 6.1.1 on 2026-09-10 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='bus_number',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='driver',
            name='destination_stop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_dest_stops', to='tracker.busstop'),
        ),
        migrations.AddField(
            model_name='driver',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers', to='tracker.route'),
        ),
        migrations.AddField(
            model_name='driver',
            name='start_stop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_start_stops', to='tracker.busstop'),
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_number', models.CharField(max_length=30)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('current_latitude', models.FloatField(blank=True, null=True)),
                ('current_longitude', models.FloatField(blank=True, null=True)),
                ('current_stop_seq', models.IntegerField(default=1)),
                ('last_location_update', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('LIVE', 'Live'), ('STOPPED', 'Stopped'), ('DELAYED', 'Delayed'), ('ENDED', 'Ended')], default='LIVE', max_length=20)),
                ('stopped_since', models.DateTimeField(blank=True, null=True)),
                ('stop_reason', models.CharField(blank=True, max_length=200, null=True)),
                ('destination_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_dest_stops', to='tracker.busstop')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='tracker.driver')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='tracker.route')),
                ('start_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_start_stops', to='tracker.busstop')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='TripStopEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=200)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stop_events', to='tracker.trip')),
            ],
        ),
        migrations.DeleteModel(
            name='Bus',
        ),
    ]
